# Introduction

In this lab, we will explore the functionality and usage of multiclass and multioutput algorithms in scikit-learn. Multiclass classification is a classification task where samples are assigned to more than two classes. Multioutput classification, on the other hand, predicts multiple properties for each sample. We will cover the following topics:

- Multiclass Classification
- Multilabel Classification
- Multiclass-Multioutput Classification
- Multioutput Regression

# Multiclass Classification

## Problem Description

Multiclass classification is a classification task with more than two classes. Each sample is assigned to only one class.

## Target Format

A valid representation of multiclass targets is a 1D or column vector containing more than two discrete values.

## Example

Let's use the Iris dataset to demonstrate multiclass classification:

In [1]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier

# Load the Iris dataset
X, Y = datasets.load_iris(return_X_y=True)

# Fit a logistic regression model using OneVsRestClassifier
model = OneVsRestClassifier(LogisticRegression())
model.fit(X, Y)

# Make predictions
predictions = model.predict(X)
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# Multilabel Classification

## Problem Description

Multilabel classification is a classification task where each sample can be assigned multiple labels. The number of labels each sample can have is greater than two

## Target Format

A valid representation of multilabel targets is a binary matrix, where each row represents a sample and each column represents a class. A value of 1 indicates the presence of the label in the sample, while 0 or -1 indicates the absence.

## Example

Let's create a multilabel classification problem using the make_classification function:

In [3]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import RandomForestClassifier

# Generate a multilabel classification problem
X, y = make_classification(n_samples=100, n_features=10, n_informative=5, random_state=42)
y = y.reshape(-1, 1)

# Fit a multioutput random forest for classifier
model = MultiOutputClassifier(RandomForestClassifier())
model.fit(X, y)

# Make predictions
predictions = model.predict(X)
print(predictions)

[[0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]]


# Multiclass-Multioutput Classification

## Problem Description

Multiclass-multioutput classification, also known as multitask classification, predicts multiple non-binary properties for each sample. Each property can have more than two classes.

## Target Format

A valid representation of multiclass-multioutput targets is a dense matrix, where each row represents a sample and each column represents a different property or class.

## Example

Let's create a multiclass-multioutput classification problem using the make_classification function:

In [7]:
from sklearn.datasets import make_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.svm import SVC
import numpy as np

# Create multiple target arrays
X, y1 = make_classification(n_samples=100, n_features=10, n_informative=5, n_classes=3, random_state=0)
_, y2 = make_classification(n_samples=100, n_features=10, n_informative=5, n_classes=3, random_state=1)

# Stack them as a 2D array: shape (100, 2)
y = np.column_stack((y1, y2))

# Fit a multioutput support vector classifier
model = MultiOutputClassifier(SVC())
model.fit(X, y)

# Make predictions
predictions = model.predict(X)
print(predictions.shape)  # should be (100, 2)


(100, 2)


# Multioutput Regression

## Problem Description

Multioutput regression predicts multiple numerical properties for each sample. Each property is a numerical variable, and the number of properties can be greater than or equal to two.

## Target Format

A valid representation of multioutput regression targets is a dense matrix, where each row represents a sample and each column represents a different property.

## Example

Let's create a multioutput regression problem using the make_regression function:

In [8]:
from sklearn.datasets import make_regression
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import LinearRegression

# Generate a multioutput regression problem
X, y = make_regression(n_samples=100, n_features=10, n_targets=3, random_state=0)

# Fit a multioutput linear regression model
model = MultiOutputRegressor(LinearRegression())
model.fit(X, y)

# Make predictions
predictions = model.predict(X)
print(predictions)

[[ 386.40928649  489.45939394  511.26504808]
 [-420.85720458 -242.87078353 -243.3526257 ]
 [-531.3081273  -328.08104892 -380.67082752]
 [  59.8479058   115.75632017  127.45092232]
 [-301.14309399 -109.75582023 -118.10046999]
 [ 330.23664021  160.38092687  211.73437962]
 [ -51.32278088  -54.57647045  -43.81111988]
 [-348.36770587 -153.61343    -197.29736509]
 [ -52.27001642  -22.79439027    4.27864745]
 [  32.71918238  -63.50248726    1.07479876]
 [  38.91407303  -39.06803354  -45.78345534]
 [ 147.78471964   91.59271639  133.29104412]
 [ 200.39557445  233.97822447  311.49595322]
 [-430.35262667 -316.69089669 -401.62651282]
 [  77.9708449   -83.33288201 -122.34163175]
 [ -22.97630556  213.9634942   152.43942553]
 [-332.1485845  -134.8797029  -155.11440523]
 [-309.16780465  -13.69034685  -94.44911924]
 [-180.91116196 -137.34175145 -120.64587587]
 [-317.46158048 -146.22183428 -229.01713302]
 [  25.64753966   -2.74537018  -46.96177624]
 [-107.61122863  -18.47334034 -101.46569475]
 [-107.407

# Summary

In this lab, we explored multiclass and multioutput algorithms in scikit-learn. We covered multiclass classification, multilabel classification, multiclass-multioutput classification, and multioutput regression. These algorithms allow us to solve complex classification and regression tasks with multiple targets or classes.