# Introduction

Biclustering is a method that simultaneously clusters rows and columns of a data matrix. This allows us to identify submatrices within the data matrix that have specific properties. Biclustering is useful in various domains, including data analysis, image processing, and bioinformatics.

In this lab, we will learn how to perform biclustering using the **sklearn.cluster.bicluster** module in scikit-learn. We will explore two common biclustering algorithms: Spectral Co-Clustering and Spectral Biclustering. These algorithms differ in how they define and assign rows and columns to biclusters.

# Import necessary libraries and dataset

First, let's import the necessary libraries and load a sample dataset that we will use for biclustering.

In [1]:
import numpy as np
from sklearn.cluster import SpectralCoclustering, SpectralBiclustering

# Load sample data
data = np.arange(100).reshape(10, 10)

# Perform Spectral Co-Clustering

Now, let's perform biclustering using the Spectral Co-Clustering algorithm. This algorithm finds biclusters with higher values compared to other rows and columns.

In [2]:
# Initialize and fit the Spectral Co-Clustering model
model_co = SpectralCoclustering(n_clusters=3, random_state=0)
model_co.fit(data)

# Get row and column cluster membership
row_clusters_co = model_co.row_labels_
column_clusters_co = model_co.column_labels_

# Perform Spectral Biclustering

Next, let's perform biclustering using the Spectral Biclustering algorithm. This algorithm assumes that the data matrix has a hidden checkerboard structure.

In [3]:
# Initialize and fit the Spectral Biclustering model
model_bi = SpectralBiclustering(n_clusters=(2, 3), random_state=0)
model_bi.fit(data)

# Get row and column cluster membership
row_clusters_bi = model_bi.row_labels_
column_clusters_bi = model_bi.column_labels_

# Visualize the results

Finally, let's visualize the bicluster structures obtained from the Spectral Co-Clustering and Spectral Biclustering algorithms.

In [4]:
# Visualization for Spectral Co-Clustering
print("Spectral Co-Clustering:")
print("Row clusters:")
print(row_clusters_co)
print("Column clusters:")
print(column_clusters_co)

# Visualization for Spectral Biclustering
print("\nSpectral Biclustering:")
print("Row clusters:")
print(row_clusters_bi)
print("Column clusters:")
print(column_clusters_bi)

Spectral Co-Clustering:
Row clusters:
[1 2 2 2 2 2 2 0 2 0]
Column clusters:
[0 2 0 0 0 2 2 2 2 2]

Spectral Biclustering:
Row clusters:
[0 0 0 0 0 1 1 1 1 1]
Column clusters:
[0 0 0 2 2 2 2 1 1 1]


# Summary

In this lab, we learned how to perform biclustering using the Spectral Co-Clustering and Spectral Biclustering algorithms in scikit-learn. Biclustering allows us to simultaneously cluster rows and columns of a data matrix to identify submatrices with specific properties. Biclustering can be useful in various data analysis tasks, such as identifying patterns in gene expression data or finding structure in image datasets.